# Generated by Django 3.0.6 on 2020-06-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20200626_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
