# Generated by Django 3.0.6 on 2020-06-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(related_name='blogs_posts', to='blogs.Comment'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
