# Generated by Django 3.0.6 on 2020-06-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20200626_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
