# Generated by Django 3.0.6 on 2020-06-26 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_auto_20200626_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
    ]
