# Generated by Django 3.0.6 on 2020-06-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_auto_20200626_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved',
            field=models.CharField(choices=[('approved', 'approved'), ('notapproved', 'notapproved')], default='approved', help_text='Set to "approved" to make this post publicly visible', max_length=20),
        ),
    ]
